### ISSUE TITLE
Documentation Site is not working

### ISSUE THREAD

**Issue by RotterAxel** [LGouellec/streamiz#355]
Description
===========
The documentation page is not working. https://lgouellec.github.io/kafka-streams-dotnet/

How to reproduce
================
Try to open the link to the documentation site: https://lgouellec.github.io/kafka-streams-dotnet/

Checklist
=========
![image](https://github.com/user-attachments/assets/3f8e9298-afe6-4fff-852b-d1dafff62084)
![image](https://github.com/user-attachments/assets/252484bb-1003-4209-ad2d-5b55a80c01cc)
![image](https://github.com/user-attachments/assets/9be90d09-d2d5-4160-8a60-24198214c9dc)
![image](https://github.com/user-attachments/assets/988b54a5-bdb6-4be8-83ec-c8c1d2a8ea20)

**Comment by LGouellec** [comment]
Hey @RotterAxel, 

Thanks for your issue. I will look at it.

**Comment by LGouellec** [comment]
Hey @RotterAxel , 

Please use the new link : [lgouellec.github.io/streamiz/](https://lgouellec.github.io/streamiz/)

Best regards,
