### ISSUE TITLE
Help with Aggregate values to Hashset<T>

### ISSUE THREAD

**Issue by PolyakovPavel** [LGouellec/streamiz#390]
Description
===========
Hello. I'm trying to get a table with aggregations by key and value Hash<Guid>
But for some reason, in the hash, only the last value of the key is always indicated. Tell me, what could be the problem?

My code:

    var account_users =  builder
        .Table("user_account_stream", new Int32SerDes(), new KafkaJsonDeserializer<UserAccount>())
        .GroupBy<int, UserAccount, Int32SerDes, KafkaJsonDeserializer<UserAccount>>((k, v) => KeyValuePair.Create(k, v))
        .Aggregate
        (
            () => new HashSet<Guid>(),
            (k, v, old) =>
            {
                old.Add(v.UserId);
                return old;
            },
            (k, v, old) =>
            {
                old.Remove(v.UserId);
                return old;
            },
            RocksDb.As<int, HashSet<Guid>>("agg-store")
                .WithKeySerdes<Int32SerDes>()
                .WithValueSerdes(new KafkaJsonDeserializer<HashSet<Guid>>())
        );

Version Streamiz.Kafka.Net 1.6.0

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] A code snippet with your topology builder (ex: builder.Stream<string, string>("topic").to("an-another-topic");)
 - [ ] Streamiz.Kafka.Net nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with in debug mode (log4net and StreamConfig.Debug) as necessary in configuration).
 - [ ] Critical issue.

**Comment by LGouellec** [comment]
Hi @PolyakovPavel , 

Thanks for your issue.  If I understand correctly, you want to maintain a list of GUID per key, so you don't need to implement the `subtractor` in your aggregate function. Because otherwise you will remove the old GUID and add the new one, so at any moment the hashset will contains only 0 or 1 GUID.

Quick example with a reproducer which match your use case : 
``` csharp

public class Issue390Tests
{
    private class UserAccount
    {
        public string UserId { get; set; }
        public string Login { get; set; }
    }
    
    [Test]
    public void ReproducerTest()
    {
        var streamConfig = new StreamConfig();
        streamConfig.ApplicationId = "test-reproducer-issue390";
        
        var builder = new StreamBuilder();
        
        var account_users =  builder
            .Table("user_account_stream", new Int32SerDes(), new JsonSerDes<UserAccount>())
            .GroupBy<int, UserAccount, Int32SerDes, JsonSerDes<UserAccount>>((k, v, r) => KeyValuePair.Create(k, v))
            .Aggregate
            (
                () => new HashSet<string>(),
                (k, v, old) =>
                {
                    old.Add(v.UserId);
                    return old;
                },
                (k, v, old) => old,
                RocksDb.As<int, HashSet<string>>("agg-store")
                    .WithKeySerdes<Int32SerDes>()
                    .WithValueSerdes(new JsonSerDes<HashSet<string>>())
            );

        using var driver = new TopologyTestDriver(builder.Build(), streamConfig);
        var users = driver.CreateInputTopic<Int32, UserAccount, Int32SerDes, JsonSerDes<UserAccount>>("user_account_stream");
        users.PipeInput(1, new UserAccount(){UserId = Guid.NewGuid().ToString(), Login = "slegouellec"});
        users.PipeInput(1, new UserAccount(){UserId = Guid.NewGuid().ToString(), Login = "mlga"});

        var store = driver.GetKeyValueStore<int, HashSet<string>>("agg-store");
        var items = store.All().ToList();
        Assert.AreEqual(1, items.Count);
        Assert.AreEqual(1, items[0].Key);
        Assert.AreEqual(2, items[0].Value.Count);
    }
}
``` 

Please let me know if you have any futher questions

**Comment by PolyakovPavel** [comment]
Thank you! I Undestend now my mistake.
